# Generated by Django 5.2.10 on 2026-02-09 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "resource",
                    models.CharField(
                        help_text="Microsoft Graph resource path (e.g., /teams/{id}/channels/{id}/messages)",
                        max_length=500,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        help_text="Comma-separated list: created, updated, deleted",
                        max_length=100,
                    ),
                ),
                ("notification_url", models.URLField(help_text="Webhook endpoint URL")),
                (
                    "expiration_datetime",
                    models.DateTimeField(help_text="When the subscription expires"),
                ),
                (
                    "client_state",
                    models.CharField(
                        help_text="Secret token for validation", max_length=255
                    ),
                ),
                ("lifecycle_notification_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("deleted", "Deleted"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team_id",
                    models.CharField(
                        blank=True,
                        help_text="Teams team ID if applicable",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        blank=True,
                        help_text="Teams channel ID if applicable",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "expiration_datetime"],
                        name="msgraph_int_status_093035_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamsWebhookNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(
                        help_text="Unique ID from Microsoft Graph", max_length=255
                    ),
                ),
                (
                    "graph_subscription_id",
                    models.CharField(
                        db_index=True,
                        help_text="Subscription ID from notification",
                        max_length=255,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        help_text="created, updated, or deleted", max_length=50
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        help_text="Resource path from notification", max_length=500
                    ),
                ),
                (
                    "resource_data_id",
                    models.CharField(
                        blank=True,
                        help_text="Resource ID (e.g., message ID)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("tenant_id", models.CharField(blank=True, max_length=255, null=True)),
                ("team_id", models.CharField(blank=True, max_length=255, null=True)),
                ("channel_id", models.CharField(blank=True, max_length=255, null=True)),
                ("message_id", models.CharField(blank=True, max_length=255, null=True)),
                ("payload", models.JSONField(help_text="Full notification payload")),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this notification has been processed",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="msgraph_integration.graphsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["graph_subscription_id", "-received_at"],
                        name="msgraph_int_graph_s_09d4bb_idx",
                    ),
                    models.Index(
                        fields=["processed", "-received_at"],
                        name="msgraph_int_process_8dcc48_idx",
                    ),
                ],
            },
        ),
    ]
