# Generated by Django 5.2.10 on 2026-02-21 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgraph_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAssistantSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('query', models.TextField()),
                ('request_type', models.CharField(choices=[('chat', 'Chat'), ('raw_search', 'Raw Search')], db_index=True, max_length=20)),
                ('account_identifier', models.CharField(blank=True, help_text='User email or account name captured at request time.', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_assistant_search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['request_type', '-requested_at'], name='msgraph_int_request_be79d8_idx')],
            },
        ),
    ]
