# Generated by Django 5.2.5 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotionContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notion_id", models.CharField(max_length=64, unique=True)),
                ("object_type", models.CharField(choices=[("page", "Page"), ("database", "Database")], max_length=16)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("url", models.URLField(blank=True, default="", max_length=1024)),
                ("parent_type", models.CharField(blank=True, default="", max_length=64)),
                ("parent_notion_id", models.CharField(blank=True, default="", max_length=64)),
                ("last_edited_time", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("plain_text", models.TextField(blank=True, default="")),
                ("raw_metadata", models.JSONField(blank=True, default=dict)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_edited_time", "-synced_at"],
            },
        ),
    ]
