# Generated by Django 5.2.5 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notion_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notioncontent",
            name="content_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="notioncontent",
            name="last_ingested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notioncontent",
            name="rag_document_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
